module.exports={
    username:"root",
    password:"ANSKk08aPEDbFjDO",
    database:"testing",
    host:"localhost",
    dialect:"mysql",
    port:3307,
    define:{
      timestamps:true,
      underscored:true
    }
}